apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sinatra
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
      - name: sinatra
        image: sinatra-app:v1
        ports:
        - containerPort: 4567
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
