apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-kubernetes
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
